[package]
name = "mysurrealdb"
publish = false
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
failure = "0.1.8"
futures = "0.3.5"
log = "0.4.8"
maplit = "1.0.2"
nom = "5.1.2"
regex = "1.3.9"
http = "0.2"
bytes = "0.5.5"

[dependencies.ctx]
version = "0.2.0"
package = "io-context"

[dependencies.dec]
version = "1.6.0"
package = "rust_decimal"
features = ["serde-float"]

[dependencies.fern]
version = "0.6.0"
features = ["colored"]

[dependencies.uuid]
version = "0.8.1"
features = ["serde", "v4"]

[dependencies.warp]
version = "0.2.3"
features = ["compression", "websocket"]

[dependencies.tokio]
version = "0.2"
features = ["macros"]

[dependencies.reqwest]
version = "0.10.6"
features = ["blocking"]

[dependencies.chrono]
version = "0.4.11"
features = ["serde"]

[dependencies.serde]
version = "1.0.111"
features = ["derive"]

[dependencies.serde_cbor]
version = "0.11.1"

[dependencies.serde_json]
version = "1.0.55"
