[package]
name = "mysurrealdb"
publish = false
edition = "2018"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.53"
argon2 = "0.3.2"
async-recursion = "1.0.0"
bincode = "1.3.3"
byteorder = "1.4.3"
bytes = "1.1.0"
clap = "3.0.10"
dmp = "0.1.1"
echodb = "0.2.0"
futures = "0.3.19"
fuzzy-matcher = "0.3.7"
http = "0.2.6"
hyper = "0.14.16"
log = "0.4.14"
md-5 = "0.10.0"
nanoid = "0.4.0"
nom = "7.1.0"
once_cell = "1.9.0"
pbkdf2 = "0.10.0"
rand = "0.8.4"
regex = "1.5.4"
scrypt = "0.8.1"
sha-1 = "0.10.0"
sha2 = "0.10.1"
slug = "0.1.4"
thiserror = "1.0.30"
url = "2.2.2"
utf-8 = "0.7.6"

[dependencies.dec]
version = "1.20.0"
package = "rust_decimal"
features = ["maths", "serde-float"]

[dependencies.geo]
version = "0.18.0"
features = ["use-serde"]

[dependencies.fern]
version = "0.6.0"
features = ["colored"]

[dependencies.uuid]
version = "0.8.2"
features = ["serde", "v4"]

[dependencies.warp]
version = "0.3.2"
features = ["compression", "websocket"]

[dependencies.tikv]
version = "0.1.0"
package = "tikv-client"

[dependencies.tokio]
version = "1.15.0"
features = ["macros"]

[dependencies.reqwest]
version = "0.11.9"
features = ["blocking"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.serde]
version = "1.0.135"
features = ["derive"]

[dependencies.serde_cbor]
version = "0.11.2"

[dependencies.serde_json]
version = "1.0.78"

[dependencies.serde_pack]
version = "1.0.0"
package = "rmp-serde"
