[package]
name = "mysurrealdb"
publish = false
edition = "2018"
version = "0.0.0"

[workspace]
members = ["lib"]

[profile.release]
lto = true
strip = true
opt-level = 3
panic = 'abort'
codegen-units = 1

[dependencies]
argon2 = "0.4.0"
base64 = "0.13.0"
bytes = "1.1.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.1.18"
fern = { version = "0.6.1", features = ["colored"] }
futures = "0.3.21"
http = "0.2.7"
hyper = "0.14.18"
jsonwebtoken = "8.1.0"
log = "0.4.17"
once_cell = "1.10.0"
rand = "0.8.5"
reqwest = { version = "0.11.10", features = ["blocking"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.81"
serde_pack = { version = "1.1.0", package = "rmp-serde" }
surrealdb = { path = "lib" }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["macros"] }
warp = { version = "0.3.2", features = ["compression", "tls", "websocket"] }
