[package]
name = "mysurrealdb"
publish = false
edition = "2018"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.40"
bytes = "1.0.1"
clap = "2.33.3"
futures = "0.3.13"
http = "0.2.3"
log = "0.4.14"
maplit = "1.0.2"
nom = "6.1.2"
regex = "1.4.5"
thiserror = "1.0.24"
wasm-bindgen = "0.2.72"
xid = "1.0.0"

[dependencies.dec]
version = "1.10.3"
package = "rust_decimal"

[dependencies.fern]
version = "0.6.0"
features = ["colored"]

[dependencies.uuid]
version = "0.8.2"
features = ["serde", "v4"]

[dependencies.warp]
version = "0.3.1"
features = ["compression", "websocket"]

[dependencies.tokio]
version = "1.4.0"
features = ["macros"]

[dependencies.reqwest]
version = "0.11.2"
features = ["blocking"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.serde]
version = "1.0.125"
features = ["derive"]

[dependencies.serde_cbor]
version = "0.11.1"

[dependencies.serde_json]
version = "1.0.64"